package kom

const (
	APP_TIME_ZONE  = "APP_TIME_ZONE"
	APP_ETCD_OPEN  = "APP_ETCD_OPEN"
	APP_PPROF_OPEN = "APP_PPROF_OPEN"
	SERV_HOST      = "SERV_HOST"
	SERV_PORT      = "SERV_PORT"
	SERV_TTL       = "SERV_TTL"
	SERV_NAME      = "SERV_NAME"
	SERV_GROUP     = "SERV_GROUP"
	SERV_WEIGHT    = "SERV_WEIGHT"
	SERV_VERSION   = "SERV_VERSION"
	ETCD_TIMEOUT   = "ETCD_TIMEOUT"
	ETCD_USERNAME  = "ETCD_USERNAME"
	ETCD_PASSWORD  = "ETCD_PASSWORD"
	ETCD_NAMESPACE = "ETCD_NAMESPACE"
	ETCD_ENDPOINTS = "ETCD_ENDPOINTS"
)
