version: 3.0

listen:
  host: 127.0.0.1
  port: 8080
  group: default
  name: test.service
  weight: 100
etcd:
  endpoints:
    - 127.0.0.1:2345
  timeout: 30
  username: root
  password: root
  namespace: default
zap:
  env: prod # prod|dev|test
  level: info
  open_tracing: On
  logger:
    filename: /path/to/log.log
    maxsize: 100
    maxage: 100
    maxbackups: 1
    localtime: true
    compress: true
app:
  time_zone: Asia/Shanghai
  pprof_open: On
